### ISSUE TITLE
Permissions parameter in createUser method is not properly serialized 

### ISSUE THREAD

**Issue by JuanCarlosGonzalez** [ExaVault/evapi-java#3]
The api expects a comma separated string with the permissions. The parameter type is a List which is not serialized according to that pattern if String.valueOf(List) is used.

**Comment by dylangleason** [comment]
This has been resolved as of commit 517125f7ccd2908a2efc91ef012d647d86f57a05. The API documentation incorrectly specified the permissions parameter as an array, when it should have been a string type. This has been refactored and tested and working correctly.

Additionally, parameters specified as arrays (e.g. filePaths[]=val1&filePaths[]=val2) are now properly serialized and in the expected format.
