### ISSUE TITLE
Can't push local branch with several fixes

### ISSUE THREAD

**Issue by JuanCarlosGonzalez** [ExaVault/evapi-java#4]
I'd like to push a local brach with several fixes in order to make a pull request for approval.

**Comment by dylangleason** [comment]
Juan, did you make sure to create a new branch with your changes? This documentation should provide you with the information you need: https://help.github.com/articles/creating-a-pull-request/

**Comment by dylangleason** [comment]
Oh, it appears you must first fork a copy of the repo before you can do this. Here is a tutorial on how to do this: http://yangsu.github.io/pull-request-tutorial/

**Comment by JuanCarlosGonzalez** [comment]
Hi Dylan.

I've haven't tried again since last week. I've seen that I've been granted
access to the repo so I think it should work now. Currently I'm working
integrating your java library in our development so may be there are more
changes/fixes. I'll let you know when I try again.

Thank you very much.

On Mon, Mar 16, 2015 at 6:03 PM, Dylan Gleason notifications@github.com
wrote:

> Juan, did you make sure to create a new branch with your changes? This
> documentation should provide you with the information you need:
> https://help.github.com/articles/creating-a-pull-request/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ExaVault/evapi-java/issues/4#issuecomment-81811005.

## 

---

 Juan Carlos González González
 PentaSoft Marketing, S.L.
 Empresa certificada ISO 9001:2000
 C/ Valentín Beato, 24, 3º Oficina 10
 28037 Madrid
 Tfno: +34 91 375 13 00 ( Ext. 1102 )
 Fax:  +34 91 375 15 11
 www.pentasoft.es
 www.seekky.com

Este mensaje contiene información propietaria de la cual parte o toda puede
contener información confidencial o protegida legalmente. Está
exclusivamente destinado al usuario de destino. Si, por un error de envío o
transmisión, ha recibido este mensaje y usted no es el destinatario del
mismo, por favor, notifique este hecho al remitente. Si no es el
destinatario final de este mensaje, no debe usar, informar, distribuir,
imprimir, copiar o difundir este mensaje bajo ningún medio. POR FAVOR,
ANTES DE IMPRIMIR ESTE CORREO ELECTRÓNICO CONSIDERE SI ES REALMENTE
NECESARIO. REDUCIRÁ EL CONSUMO DE PAPEL.

This message contains information from PentaSoft which may be confidential
and privileged. If you are not an intended recipient, please refrain from
any disclosure, copying, distribution or use of this information and note
that such actions are prohibited. If you have received this transmission in
error, please notify by email to the sender. PLEASE, BEFORE PRINTING THIS
EMAIL, CONSIDER IF IT IS REALLY NECESSARY. IT WILL REDUCE THE CONSUMPTION
OF PAPER.

---

**Comment by dylangleason** [comment]
Juan, I mistakenly added you to the repo, as the pull request model requires forking the repo first. I apologize for the confusion.

**Comment by JuanCarlosGonzalez** [comment]
Hi again. 

Yes, you may fork or clone any (public) git repo in order to collaborate. I decided to clone your repo and currently working on a local branch. Once integrated in our development, I'll come back with my local branch and I'll generate a pull request in order you can view my changes and if they are OK, then you should approve them and then merge them.

**Comment by dylangleason** [comment]
Pull request has been addressed and merged with master.
