### ISSUE TITLE
Issue in FilesAndFoldersApiTest

### ISSUE THREAD

**Issue by gw212** [ExaVault/evapi-java#9]
Checking out a new copy of the source code, there's errors in the FilesAndFoldersApiTest.java file.  It looks like some of the methods in FilesAndFoldersApi have had their signatures changes.  They are the following:
copyResources
createFolder
moveResources
renameResource

All of these are expecting 4 strings as parameters but are only provided one string and an object.

**Comment by amythelangill** [comment]
Those tests are totally auto-generated by swagger when the libraries are created. We'll check into why the tests don't make any sense.

**Comment by AmyExaVault** [comment]
The latest version of the libraries includes the various signature changes.
